///////////////////////////////////////////////////////////
//  Employee.cs
//  Implementation of the Class Employee
//  Generated by Enterprise Architect
//  Created on:      26-Sep-2024 9:34:54 AM
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Employee {

	private DateTime birthDate;
	private string name;
	private double salary;

	public Employee(){

	}

	~Employee(){

	}

	public DateTime BirthDate{
		get{
			return birthDate;
		}
		set{
			birthDate = value;
		}
	}

	public string GetDetails(){

		return "";
	}

	public string Name{
		get{
			return name;
		}
		set{
			name = value;
		}
	}

	public double Salary{
		get{
			return salary;
		}
		set{
			salary = value;
		}
	}

}//end Employee