///////////////////////////////////////////////////////////
//  Engineer.cs
//  Implementation of the Class Engineer
//  Generated by Enterprise Architect
//  Created on:      26-Sep-2024 9:34:55 AM
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Engineer : Employee {

	public Engineer(){

	}

	~Engineer(){

	}

	public override DateTime BirthDate{
		get{
			return birthDate;
		}
		set{
			birthDate = value;
		}
	}

	public override string GetDetails(){

		return "";
	}

	public override string Name{
		get{
			return name;
		}
		set{
			name = value;
		}
	}

	public override double Salary{
		get{
			return salary;
		}
		set{
			salary = value;
		}
	}

}//end Engineer